### ISSUE TITLE
Results and Tensorflow implementation

### ISSUE THREAD

**Issue by maesfahani** [hazirbas/poselstm-pytorch#1]
Hi,
I saw in the paper that your implementation is with Tensorflow.
Since the result of pythorch is not that promising, did you release the tensorflow implementation of your work?
Is there any difference between this implementation and the paper?
Thanks

**Comment by hazirbas** [comment]
Hi,
the results change a lot by simply changing the platform. Unfortunately, Tensorflow trainings were undeterministic and I dont think one can get the same results ever again. Plus I m using the hyperparameters, chosen in the paper. Therefore, my deterministic results are not optimized for the best hyperparams.

There is no difference in the implementation.
