### ISSUE TITLE
Could you please offer the trained parameters?

### ISSUE THREAD

**Issue by pkuanjie** [hazirbas/poselstm-pytorch#12]
It is a great implementation of the two camera pose estimation papers. Thank you for your work! It would be even better if you could offer the trained parameters of PoseNet and PostLSTM :-)

**Comment by hazirbas** [comment]
Hey,
all models are downloadable, from the table [here](https://github.com/hazirbas/poselstm-pytorch#optimization-scheme-and-loss-weights).
