### ISSUE TITLE
what beta refers

### ISSUE THREAD

**Issue by shenzhenBUAA** [hazirbas/poselstm-pytorch#15]
Thank you for your help! when  I am training my data, I can not understand one of those params, beta refers.  You have written in README.txt that different scenes use the different beta, but I do not know which number exactly fits my dataset. my dataset is a 9m*6m football grassland.
plus, I am not a  native English speaker, there may be something I expressed is not very clear.QAQ

**Comment by hazirbas** [comment]
hey, you could do some grid search and try to see what beta works for your case.

**Comment by shenzhenBUAA** [comment]
thanks,are there any references about grid search specially for this project?

**Comment by hazirbas** [comment]
no, it is a general approach
