### ISSUE TITLE
Class Activation Map as Visualization

### ISSUE THREAD

**Issue by Yingyan-Xu** [hazirbas/poselstm-pytorch#2]
Hi,
how did you draw the class activation map (CAM) in the paper? I mean that CAM is often used for a classification problem and how does it work for a regression problem (i.e. when the output vector is composed of continuous values rather than probabilities)?

**Comment by hazirbas** [comment]
Hi,
To be honest, I do not remember fully as the first author worked on the activation map generation. In case I find some piece of code around, i ll let you know.
