### ISSUE TITLE
lstm_hidden_size value

### ISSUE THREAD

**Issue by DanielCoelho112** [hazirbas/poselstm-pytorch#22]
Hi @hazirbas,

congrats for this implementation. Great job.

According to the architecture of the network:
![image](https://user-images.githubusercontent.com/73063947/174435623-9b61ac61-e420-455e-b023-54b0f2df2fb3.png)

I believe that the lstm_hidden_size should be 128 and not 256 as it currently is. What do you say? Do you want me to do a pull request to fix it, or there is some reason that I'm not seeing for the 256?

**Comment by hazirbas** [comment]
Hi @DanielCoelho112 , thanks for flagging it. Changing it in the code will break the models trained. It is probably a mistake in the visualization or in the code. Let's not change it for now.

**Comment by hazirbas** [comment]
If you want tho, feel free to fork, fix it and publish the new models!
