### ISSUE TITLE
 The pretrained model

### ISSUE THREAD

**Issue by 18pxrsun** [hazirbas/poselstm-pytorch#6]
The link of pretrained model is unable opened，could you publish it again？Thank you very much.

**Comment by hazirbas** [comment]
Which one? I am able to download the models.

**Comment by 18pxrsun** [comment]
https://vision.in.tum.de/webarchive/hazirbas/poselstm-pytorch/places-googlenet.pickle
When I open this link, it's garbled.Would you send it to my email? pxrsun@163.com

**Comment by hazirbas** [comment]
I can download and read the file. If you are using Python 2 use the following to read:
`with open('places-googlenet.pickle', 'rb') as f:
    print( pickle.load(f).keys())
`

**Comment by 18pxrsun** [comment]
I can't download the file.So I don't have the places-googlenet.pickle.

**Comment by hazirbas** [comment]
Did you try using wget? It works for me.

**Comment by 18pxrsun** [comment]
I can download it by using wget,thank you very much.
